# Generated by Django 4.0.4 on 2022-05-12 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.DateField(default=datetime.date(2022, 6, 11)),
        ),
    ]
