# Generated by Django 4.0.4 on 2022-05-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_membership_duration_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.DateField(default=datetime.date(2022, 6, 13)),
        ),
    ]
