# Generated by Django 4.0.4 on 2022-05-16 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_membership_duration_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration_period',
            field=models.DateField(default=datetime.date(2022, 6, 15)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Emerald', 'Emerald'), ('Jasper', 'Jasper'), ('Onynx', 'Onynx'), ('Obsidian', 'Obsidian'), ('Pearl', 'Pearl'), ('Ruby', 'Ruby'), ('Sapphire', 'Sapphire'), ('Topaz', 'Topaz'), ('Opal', 'Opal'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], default='Free', max_length=40),
        ),
    ]
