# Generated by Django 4.0.4 on 2022-05-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_name',
            new_name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
