# Generated by Django 4.0.4 on 2022-05-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0007_alter_membership_duration_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('withdrawal_amount', models.IntegerField()),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='subscription.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_task1', models.CharField(max_length=250, null=True)),
                ('youtube_task2', models.CharField(max_length=250, null=True)),
                ('youtube_link1', models.CharField(max_length=250, null=True)),
                ('youtube_link2', models.CharField(max_length=250, null=True)),
                ('youtube_link3', models.CharField(max_length=250, null=True)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='subscription.subscription')),
            ],
        ),
    ]
