# Generated by Django 4.0.4 on 2022-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_youtube_task3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='withdrawal_amount',
            field=models.IntegerField(default=0),
        ),
    ]
