# Generated by Django 4.0.4 on 2022-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_userwallet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='entered_date',
            field=models.DateField(auto_now=True),
        ),
    ]
