# Generated by Django 4.0.4 on 2022-06-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_userwallet_entered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
